---

- hosts: pi-backup
  vars:
    pi_public_keys:
      - data/pi-key.pub
    borgbak_pool: "/data/repos"
  vars_files:
    - data/borgclients.yml
  become: true
  roles:
    - role: pibasesec
      tags: base
    - role: raspbiantesting
      tags: raspbiantesting
    - role: borgbackup
      tags: borg
  
