---
- name: Add authorized keys for user pi
  authorized_key: user=pi
                  key="{{ lookup('file', item) }}"
  with_items: "{{pi_public_keys}}"

- name: Disable empty password login
  lineinfile: dest="/etc/ssh/sshd_config" regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"
  notify: restart sshd

- name: Disable remote root login
  lineinfile: dest="/etc/ssh/sshd_config" regexp="^#?PermitRootLogin" line="PermitRootLogin no"
  notify: restart sshd

- name: Disable password login
  lineinfile: dest="/etc/ssh/sshd_config" regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"  
  notify: restart sshd

- name: Enable PAM
  lineinfile: dest="/etc/ssh/sshd_config" regexp="^#?UsePAM" line="UsePAM yes"
  notify: restart sshd